### ISSUE TITLE
NetSimile fails with string-labeled nodes

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#153]
```python
>>> import networkx as nx
>>> G = nx.florentine_families_graph()
>>> H = nx.karate_club_graph()
>>> NetSimile().dist(G, H)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/main/git/netrd/netrd/distance/netsimile.py", line 83, in dist
    G1_node_features = feature_extraction(G1)
  File "/home/main/git/netrd/netrd/distance/netsimile.py", line 132, in feature_extraction
    for n in node_list
  File "/home/main/git/netrd/netrd/distance/netsimile.py", line 132, in <listcomp>
    for n in node_list
TypeError: list indices must be integers or slices, not str
```

Not sure I really care about fixing this at this point, but something to note.

**Comment by leotrs** [comment]
I'm fairly certain that on the day of the collabathon I said that we're assuming that all nodes are labeled by integers starting at zero.

**Comment by sdmccabe** [comment]
At some point in the future it would make sense to enforce this. There are many things that are higher priority though.
